---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-facts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-facts-app
  template:
    metadata:
      labels:
        app: cat-facts-app
    spec:
      containers:
        - name: app
          image: cat-app:v1
          ports:
            - containerPort: 8000
          env:
            - name: CAT_API_URL
              valueFrom:
                configMapKeyRef:
                  name: cat-facts-config
                  key: CAT_API_URL
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000